[package]
name = "bitnuc"
version = "0.5.1"
edition = "2024"
authors = ["Noam Teyssier"]
repository = "https://github.com/noamteyssier/bitnuc"
documentation = "https://docs.rs/bitnuc"
description = "A library for efficient nucleotide sequence manipulation using 2-bit encoding"
license = "MIT"
keywords = ["bioinformatics", "dna", "sequence", "nucleotide", "2bit"]
categories = ["science::bioinformatics", "encoding", "data-structures"]

[dependencies]
fearless_simd = "0.7.0"
thiserror = "2.0.20"

[profile.release]
lto = true
codegen-units = 1

[dev-dependencies]
criterion = "0.5.1"
rand = { version = "0.10.2", default-features = false, features = ["sys_rng"] }

[[bench]]
name = "simd_comparison"
harness = false
