[package]
name = "bitnuc"
version = "0.5.0-dev"
edition = "2024"
authors = ["Noam Teyssier <noam.teyssier@arcinstitute.org"]
repository = "https://github.com/noamteyssier/bitnuc"
documentation = "https://docs.rs/bitnuc"
description = "A library for efficient nucleotide sequence manipulation using 2-bit and 4-bit encodings"
license = "MIT"
keywords = ["bioinformatics", "dna", "sequence", "nucleotide", "2bit"]
categories = ["science::bioinformatics", "encoding", "data-structures"]

[dependencies]
fearless_simd = "0.7.0"
thiserror = "2.0.20"

[features]
nosimd = []

[profile.release]
lto = true
codegen-units = 1

[dev-dependencies]
criterion = "0.5.1"
nucgen = "0.1.2"
rand = "0.8.7"

[[bench]]
name = "simd_comparison"
harness = false
